FROM emscripten/emsdk as builder

RUN apt update && apt install -y ninja-build

WORKDIR /app

COPY assets assets
COPY src src
COPY scripts scripts
COPY CMakeLists.txt CMakeLists.txt

RUN chmod +x ./scripts/*

RUN ./scripts/build-wasm-web.sh .

FROM busybox:latest

WORKDIR /app

COPY --from=builder /app/build-wasm-web/bin/* dist/
COPY --from=builder /app/releases releases/

RUN mv dist/*.html dist/index.html

RUN touch dist/httpd.conf

CMD ["busybox", "httpd", "-f", "-v", "-p", "3000", "-h", "dist", "-c", "httpd.conf"]